permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]

#excerpt_separator:  '<!-- more -->'
gems: [jekyll-paginate]

paginate: 5
paginate_path: ":num"
baseurl: ""



title: "Continuous Learning"
email: "xh@decbug.com"
description: ""
github_username:  "codejuan"
swiftype_searchId: "ahcnzwTk9sEy9JreBfZC"
disqus_shortname: "CodeJuan"



url: "http://bk.decbug.com"
imgrepo: "http://bk.decbug.com/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

